#pragma once

// Erhöhe den Fail-safe Timer auf 5 Minuten (300 Sekunden)
#ifndef CHIP_DEVICE_CONFIG_FAILSAFE_EXPIRY_LENGTH_SEC
#define CHIP_DEVICE_CONFIG_FAILSAFE_EXPIRY_LENGTH_SEC 300
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8001
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Miele & Cie. KG"
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Miele Matter Bridge"
#endif

#ifndef CHIP_DEVICE_CONFIG_TEST_SETUP_PIN_CODE
#define CHIP_DEVICE_CONFIG_TEST_SETUP_PIN_CODE 12345678
#endif

#ifndef CHIP_DEVICE_CONFIG_TEST_SETUP_DISCRIMINATOR
#define CHIP_DEVICE_CONFIG_TEST_SETUP_DISCRIMINATOR 1234
#endif

#ifndef CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 12345678
#endif

#ifndef CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 1234
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 19
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "2.3.9"
#endif

#ifndef CHIP_DEVICE_CONFIG_USE_TEST_SETUP_RESOURCES
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_RESOURCES 1
#endif
